### ISSUE TITLE
重回帰のページ、決定係数の値の範囲

### ISSUE THREAD

**Issue by wsuzume** [icoxfog417/mlnote-note#1]
決定係数は Var[ε] が Var[Y] より大きいときに負の値を取りうるので『2. 重回帰』のページの「決定係数は [0,1] の値を取り」という記述が誤りになると思います。

**Comment by icoxfog417** [comment]
ご指摘ありがとうございます。確かに、決定係数はマイナスになりえます。
ただ、決定係数がマイナスになるということは記載いただいている通り残差変動が元のデータの変動より大きくなる場合です。モデルがデータを予測する役割を持っているならば、何らかの近似により残差は元のデータの変動よりも小さくなるはずです。決定係数がマイナスになるケースは「予測モデル」と呼べないモデルといえるため、決定係数は実質的に0~1として差し支えないと思います。

参考: https://manabitimes.jp/math/1016
